title: UniMaaS Wiki
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

# Custom green color scheme
color_scheme: green

url: https://just-the-docs.github.io

# Search placeholder customization
search:
  placeholder: Search UniMaaS Wiki

# Logo path (optional - defaults to /assets/images/logo.png)
logo: /assets/images/logo.png

# External links shown in the header
aux_links:
  Project Website: https://unimaas-project.eu/

collections_dir: content
collections:
  docs:
    output: true
    permalink: /:path/

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_fold: true

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: default
